#!/usr/bin/env python3
"""Local preview server for the rdzTTGOSonde web UI (RX_FSK/data/).

Serves the LittleFS data/ folder over HTTP so the web interface can be viewed
on a desktop without flashing an ESP32. It substitutes the device-side
%PLACEHOLDER% template tokens with sample values and mocks the JSON endpoints
(/users.json, /status.json) that the pages fetch from the firmware.

Note: pages whose tabs load device-generated HTML via iframe (config.html,
status.html, qrg.html, ...) are NOT available locally -- those are produced by
the firmware's processor() at runtime, not stored as static files.

Usage:
    python3 scripts/preview_server.py [--port 8099] [--root RX_FSK/data]
"""
import argparse
import json
import os
from http.server import BaseHTTPRequestHandler, HTTPServer

PLACEHOLDERS = {
    "%VERSION_NAME%": "rdzTTGOSonde",
    "%VERSION_ID%": "devel20260615",
    "%FULLNAMEID%": "rdzTTGOSonde devel20260615",
    "%AUTODETECT_INFO%": "TTGO LoRa32 v2.1 (auto-detected)",
    "%LOCAL_UPDATES%": "",
    "%MAPCENTER%": "48.0,11.0,10",
    "%PREAUTH%": "0123456789abcdef",
    "%BOOTID%": "preview-boot-1",
}

# These pages are generated by the firmware's processor() at runtime (see
# sendConfig/sendQRG/... in RX_FSK.ino) -- they are NOT static files. Serve a
# styled placeholder so the iframe tabs don't 404 during local preview.
DEVICE_GENERATED = {
    "/qrg.html": "QRG (frequency list)",
    "/wifi.html": "WiFi configuration",
    "/status.html": "Data / status",
    "/config.html": "Configuration form",
    "/control.html": "Control",
}

STUB_TEMPLATE = """<!DOCTYPE html><html><head><meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="style.css"></head>
<body><div class="wrapper"><div class="content" style="padding:2em">
<h2>{title}</h2>
<p><em>This page is generated by the firmware on the ESP32 (processor() in
RX_FSK.ino) and has no static file. It can only be viewed on real hardware.</em></p>
</div></div></body></html>"""

MOCK_JSON = {
    "/users.json": [
        {"user": "admin", "level": 2},
        {"user": "guest", "level": 1},
    ],
    "/status.json": {
        "TTGO": "Autodetect info: TTGO LoRa32 v2.1",
        "WiFi": "connected, IP 192.168.1.42",
        "SondeHub": "uploading (last OK 3s ago)",
        "MQTT": "disabled",
        "GPS": "fix: 48.000, 11.000",
    },
}


def make_handler(root):
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *a):
            pass

        def _send(self, code, ctype, body):
            if isinstance(body, str):
                body = body.encode("utf-8")
            self.send_response(code)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_POST(self):
            # auth/user endpoints: just acknowledge so the JS doesn't error
            self._send(200, "text/plain", "ok")

        def do_GET(self):
            path = self.path.split("?")[0]
            if path in MOCK_JSON:
                self._send(200, "application/json", json.dumps(MOCK_JSON[path]))
                return
            if path in DEVICE_GENERATED:
                self._send(200, "text/html",
                           STUB_TEMPLATE.format(title=DEVICE_GENERATED[path]))
                return
            if path in ("/", ""):
                path = "/index.html"
            fp = os.path.join(root, path.lstrip("/"))
            if not os.path.isfile(fp):
                self._send(404, "text/plain", "not found: " + path)
                return
            ext = os.path.splitext(fp)[1].lower()
            ctype = {
                ".html": "text/html",
                ".css": "text/css",
                ".js": "application/javascript",
                ".json": "application/json",
                ".png": "image/png",
            }.get(ext, "text/plain")
            mode = "r" if ext in (".html", ".css", ".js", ".txt", ".json") else "rb"
            with open(fp, mode) as f:
                data = f.read()
            if ext == ".html":
                for k, v in PLACEHOLDERS.items():
                    data = data.replace(k, v)
            self._send(200, ctype, data)

    return Handler


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--host", default="0.0.0.0")
    ap.add_argument("--port", type=int, default=8099)
    ap.add_argument("--root", default=os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "RX_FSK", "data"))
    args = ap.parse_args()
    srv = HTTPServer((args.host, args.port), make_handler(args.root))
    print(f"Serving {args.root} at http://{args.host}:{args.port}")
    srv.serve_forever()


if __name__ == "__main__":
    main()
